apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-username: bXlzcWwtdXNlcm5hbWU6
    mysql-password: bXlzcWwtcGFzc3dvcmQ6
    mysql-database: bXlzcWwtZGF0YWJhc2U6
    mysql-root-password: bXlzcWwtcm9vdC1wYXNzd29yZDo=